### ISSUE TITLE
Add tap actions

### ISSUE THREAD

**Issue by douglampe** [douglampe/ha-lcars-panel#12]
Add support for tap actions following similarly convention to [button card](https://github.com/custom-cards/button-card)

Example
```
tapAction:
  action: call-service
  service: select.select_option
  data:
    entity_id: select.denon_main_zone_source
    option: SAT/CBL
```
