### ISSUE TITLE
Mixins

### ISSUE THREAD

**Issue by douglampe** [douglampe/ha-lcars-panel#46]
Add a new `mixins` root level key. This will allow specification of a set of properties to be applied to an element. You then apply the properties by using a `mixin` key.

Example:

```
mixins:
  myText:
    fontSize: 0.4
    textColor: black
    alignContent: topRight
 children:
  - type: el
    mixin: myText
    text: Cool Text
```
