### ISSUE TITLE
Add state map

### ISSUE THREAD

**Issue by douglampe** [douglampe/ha-lcars-panel#47]
Add support for a new `stateMap` key on any item. This will allow specifying keys for any state and then setting properties that apply only to that state. Item must have an entity specified. If an attribute is specified, then the attribute value will be used instead of the state.

Example:
```
  - type: el
    stateMap:
      entity: light.test
      states:
        on:
          color: orange-peel
          text: Illuminated
        off:
          color: atomic-tangerine
          text: Disengaged
```
